---
all:
  children:
    pxc_cluster:
       hosts:
         pxc1:
           ansible_host: "192.168.56.205"
           ansible_private_key_file: ".vagrant/machines/db1/virtualbox/private_key"
         pxc2:
           ansible_host: "192.168.56.206"
           ansible_private_key_file: ".vagrant/machines/db2/virtualbox/private_key"        
         pxc3:
           ansible_host: "192.168.56.207"
           ansible_private_key_file: ".vagrant/machines/db3/virtualbox/private_key"      
       vars:
         mysql_root_password: "Strongpassword"
    proxysql:
      hosts:
        psql:
          ansible_host: "192.168.56.208"
          ansible_private_key_file: ".vagrant/machines/proxysql/virtualbox/private_key"
    backends:
      hosts:
        backend:
          ansible_host: "192.168.56.209"
          ansible_private_key_file: ".vagrant/machines/backend/virtualbox/private_key"
...
