- name: Install components for building
  command: "{{ item }}"
  with_items: 
    - sudo yum install https://repo.percona.com/yum/percona-release-latest.noarch.rpm -y
    - sudo percona-release enable-only pxc-80 release
    - sudo percona-release enable tools release
    - sudo yum install MySQL-python -y
  ignore_errors: true
- name: install PXC
  yum: 
    name: percona-xtradb-cluster
    state: present
- name: start mysql
  systemd:
    name: mysql
    state: started
  
- name: store root password
  shell: "sudo grep 'temporary password' /var/log/mysqld.log | cut -b 113-124 "
  register: root_pswd
- name: update expired root user password
  shell: sudo mysql --user root --password='{{ root_pswd.stdout }}' --connect-expired-password --execute='ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
  ignore_errors: true
- name: copy my.cnf in nodes
  copy:
    content:  |
      # Template my.cnf for PXC
      # Edit to your requirements.
      [client]
      socket=/var/lib/mysql/mysql.sock

      [mysqld]
      server-id=1
      datadir=/var/lib/mysql
      socket=/var/lib/mysql/mysql.sock
      log-error=/var/log/mysqld.log
      pid-file=/var/run/mysqld/mysqld.pid

      # Binary log expiration period is 604800 seconds, which equals 7 days
      binlog_expire_logs_seconds=604800

      ######## wsrep ###############
      # Path to Galera library
      wsrep_provider=/usr/lib64/galera4/libgalera_smm.so

      # Cluster connection URL contains IPs of nodes
      #If no IP is found, this implies that a new cluster needs to be created,
      #in order to do that you need to bootstrap this node
      wsrep_cluster_address=gcomm://192.168.56.205,192.168.56.206,192.168.56.207

      # In order for Galera to work correctly binlog format should be ROW
      binlog_format=ROW

      # Slave thread to use
      wsrep_slave_threads=8

      wsrep_log_conflicts

      # This changes how InnoDB autoincrement locks are managed and is a requirement for Galera
      innodb_autoinc_lock_mode=2

      # Node IP address
      wsrep_node_address={{ node_ip }}
      # Cluster name
      wsrep_cluster_name=pxc-cluster

      #If wsrep_node_name is not specified,  then system hostname will be used
      wsrep_node_name={{ node_name }}

      #pxc_strict_mode allowed values: DISABLED,PERMISSIVE,ENFORCING,MASTER
      pxc_strict_mode=ENFORCING

      # SST method
      wsrep_sst_method=xtrabackup-v2
    dest: /etc/my.cnf
    mode: 0644
- name: create user proxysql
  shell: "{{ item }}"
  with_items: 
    - mysql -uroot -p{{ mysql_root_password }} --execute="CREATE USER 'proxysql'@'%' IDENTIFIED WITH mysql_native_password by 'Otus321$';"
    - mysql -uroot -p{{ mysql_root_password }} --execute="CREATE USER 'sbuser'@'%' IDENTIFIED WITH mysql_native_password BY 'Otus321$';"
    - mysql -uroot -p{{ mysql_root_password }} --execute="GRANT ALL PRIVILEGES ON *.* TO 'sbuser'@'%';"
  ignore_errors: true
- name: stop mysql
  systemd:
    name: mysql
    state: stopped
    






# - name: Create a new database with name 'cluster'
#   mysql_db:
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#     name: cluster
#     state: present
# - name: create_db
#   mysql_user:
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#     name: "pcs@*"
#     password: "password"
#     priv:
#       'cluster.*': 'ALL,GRANT'
